version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somedrupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
     
  web:
      build: .
      depends_on:
        - db
      
      ports:
        - "5000:80"
      restart: always
      
volumes:
    db_data: {}
